version: 0.2

env:
  variables:
    BRANCH: "master"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing git and dependencies"
      - apt-get update -y
      - apt-get install -y git
      - pip install django ruff

  pre_build:
    commands:
      - echo "Cloning the private repo using GitHub token"
      - git clone https://$GH_USER:$GH_TOKEN@github.com/aurelienkk/django-polls.git source
      - cd source
      - git checkout $BRANCH

      - echo "Running lint"
      - ruff check . || true

      - echo "Running Django tests"
      - python manage.py migrate --noinput
      - python manage.py test --noinput

  build:
    commands:
      - cd source
      - echo "Building Docker image"
      - docker build -t django-polls .

  post_build:
    commands:
      - echo "Tagging image"
      - docker tag django-polls:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - echo "Pushing image to ECR"
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
